        -->
    -->
    -->
        <acquisitionTime>600.0</acquisitionTime>
</a:observationSetting>
<a:observationSetting xmlns:tm="http://www.jmmc.fr/jmcs/models/0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:a="http://www.jmmc.fr/aspro-oi/0.1">
        <atmosphereQuality>Average</atmosphereQuality>
    can be removed
    catalogs=Simbad&amp;catalogs=Gaia%20DR3&amp;identifiers=83.82190603333%20-5.387936316139999%3B%20tet01%20Ori%20D%3B%20tet01%20Ori%20C%3B%20tet01%20Ori%20B%3B%20NAME%20Sgr%20A%2A%3BHD224803%3BaLeX%20iS%20A%3Beta%20tau%3BSirius%3B%20HD2345%3Bcoup%201%3B%20coup%202&amp;max_AO_mag=12&amp;max_FT_mag=12&amp;max_declinaison=40&amp;max_rank=20&amp;min_score=0</description>
            <category>[OB]</category>
            <category>[OB]</category>
            <category>[OB]</category>
            <color>#5BAFD6</color>
            <color>#75C147</color>
            <color>#F781BF</color>
        <date>2024-01-18</date>
        <DEC/>
        <DEC/>
        <DEC>-14.248482880310002</DEC>
        <DEC>-14.248482880310002</DEC>
        <DEC>-14.248482880310002</DEC>
        <DEC>-16.71611586111111</DEC>
        <DEC>-16.71611586111111</DEC>
        <DEC>-16.716867983351943</DEC>
        <DEC>24.105135651944444</DEC>
        <DEC>24.105135651944444</DEC>
        <DEC>36.77757263347</DEC>
        <DEC>36.77757263347</DEC>
        <DEC>36.78009900429</DEC>
        <DEC>36.78009900429</DEC>
        <DEC>36.78009900429</DEC>
        <DEC>-5.38234955363</DEC>
        <DEC>-5.38386814341</DEC>
        <DEC>-5.384027777777777</DEC>
        <DEC>-5.38521790118</DEC>
        <DEC>-5.38521790118</DEC>
        <DEC>-5.38521790118</DEC>
        <DEC>-5.38608036575</DEC>
        <DEC>-5.38608036575</DEC>
        <DEC>-5.3873151943</DEC>
        <DEC>-5.3873151943</DEC>
        <DEC>-5.38766215725</DEC>
        <DEC>-5.38766215725</DEC>
        <DEC>-5.38793078976</DEC>
        <DEC>-5.387933333333333</DEC>
        <DEC>-5.387936316139999</DEC>
        <DEC>-5.387936316139999</DEC>
        <DEC>-5.387936316139999</DEC>
        <DEC>-5.387936316139999</DEC>
        <DEC>-5.38918871984</DEC>
        <DEC>-5.389575105200833</DEC>
        <DEC>-5.389575105200833</DEC>
        <DEC>-5.389577392020833</DEC>
        <DEC>-5.389586111111111</DEC>
        <DEC>-5.3897005033</DEC>
        <DEC>-5.3897005033</DEC>
        <DEC>-5.3897005033</DEC>
        <DEC>-5.390332710439999</DEC>
        <DEC>-5.39371787728</DEC>
        <DEC>-5.395467462139999</DEC>
        <DEC>-5.395467462139999</DEC>
        <DEC>-5.39747868206</DEC>
        <DEC>-5.39747868206</DEC>
        <DEC>-5.3991079591284</DEC>
        <DEC>-5.3991079591284</DEC>
        <DEC>-5.3991079591284</DEC>
            <description>Group gathering stars used by the Fringe Tracking system</description>
            <description>Group indicating stars used by the Adaptive Optics system</description>
            <description>Group indicating stars used by the telescope guiding</description>
    <description>This file has been generated by SearchFTT for
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        <EQUINOX>2000.0</EQUINOX>
        </group>
        </group>
        </group>
        <group id="JMMC_AO">
        <group id="JMMC_FT">
        <group id="JMMC_GUIDE">
            </groupMembers>
            </groupMembers>
            </groupMembers>
            </groupMembers>
            </groupMembers>
            </groupMembers>
            </groupMembers>
            </groupMembers>
            </groupMembers>
            </groupMembers>
            </groupMembers>
            </groupMembers>
            </groupMembers>
            </groupMembers>
            </groupMembers>
            </groupMembers>
            </groupMembers>
            </groupMembers>
            </groupMembers>
            </groupMembers>
            <groupMembers>
            <groupMembers>
            <groupMembers>
            <groupMembers>
            <groupMembers>
            <groupMembers>
            <groupMembers>
            <groupMembers>
            <groupMembers>
            <groupMembers>
            <groupMembers>
            <groupMembers>
            <groupMembers>
            <groupMembers>
            <groupMembers>
            <groupMembers>
            <groupMembers>
            <groupMembers>
            <groupMembers>
            <groupMembers>
        </groupMembers>
        </groupMembers>
        <groupMembers>
        <groupMembers>
                <groupRef>JMMC_AO</groupRef>
                <groupRef>JMMC_AO</groupRef>
                <groupRef>JMMC_AO</groupRef>
                <groupRef>JMMC_AO</groupRef>
                <groupRef>JMMC_AO</groupRef>
                <groupRef>JMMC_AO</groupRef>
                <groupRef>JMMC_AO</groupRef>
                <groupRef>JMMC_AO</groupRef>
                <groupRef>JMMC_AO</groupRef>
                <groupRef>JMMC_AO</groupRef>
            <groupRef>JMMC_AO</groupRef>
                <groupRef>JMMC_FT</groupRef>
                <groupRef>JMMC_FT</groupRef>
                <groupRef>JMMC_FT</groupRef>
                <groupRef>JMMC_FT</groupRef>
                <groupRef>JMMC_FT</groupRef>
                <groupRef>JMMC_FT</groupRef>
                <groupRef>JMMC_FT</groupRef>
                <groupRef>JMMC_FT</groupRef>
                <groupRef>JMMC_FT</groupRef>
                <groupRef>JMMC_FT</groupRef>
            <groupRef>JMMC_FT</groupRef>
        <IDS>coup 1</IDS>
        <IDS>coup 2</IDS>
        <IDS>eta tau</IDS>
        <IDS>Gaia DR3 2374964121227201024</IDS>
        <IDS>Gaia DR3 2880169682463575936</IDS>
        <IDS>Gaia DR3 2880169888622006272</IDS>
        <IDS>Gaia DR3 3017363960251507712</IDS>
        <IDS>Gaia DR3 3017364059023821696</IDS>
        <IDS>Gaia DR3 3017364063323198080</IDS>
        <IDS>Gaia DR3 3017364063330465152</IDS>
        <IDS>Gaia DR3 3017364063330718080</IDS>
        <IDS>Gaia DR3 3017364063331576192</IDS>
        <IDS>Gaia DR3 3017364127743288320</IDS>
        <IDS>Gaia DR3 3017364127743288704</IDS>
        <IDS>Gaia DR3 3017364132049943680</IDS>
        <IDS>Gaia DR3 3017364132050194688</IDS>
        <IDS>Gaia DR3 3209424482420904448</IDS>
        <IDS>Gaia DR3 3209424486715714432</IDS>
        <IDS>Gaia DR3 3209424486715714816</IDS>
        <IDS>Gaia DR3 66714384142368256</IDS>
        <IDS>HD224803</IDS>
        <IDS>HD2345</IDS>
        <IDS>Sirius</IDS>
        <IDS>tet01 Ori B</IDS>
        <IDS>tet01 Ori C</IDS>
        <IDS>tet01 Ori D</IDS>
    </instrumentConfiguration>
    <instrumentConfiguration>
        <instrumentMode>MEDIUM-COMBINED</instrumentMode>
    </interferometerConfiguration>
        <minElevation>45.0</minElevation>
        <name>2MASS J05342926-0523509</name>
        <name>2MASS J05342926-0523509</name>
        <name>2MASS J05342945-0523374</name>
        <name>83.82190603333 -5.387936316139999</name>
        <name>* alf CMa B</name>
        <name>* alf CMa</name>
        <name>* alf CMa</name>
            <name>AO Star</name>
        <name>Brun 283</name>
        <name>Brun 283</name>
        <name>Brun 283</name>
        <name>COUP   885</name>
        <name>* eta Tau</name>
        <name>* eta Tau</name>
            <name>FT Star</name>
        <name>Gaia DR3 3017364063331576192</name>
        <name>Gaia DR3 66714384142368256</name>
        <name>GRAVITY</name><!--<stations>A0 G1 J2 J3</stations>
            <name>Guide Star</name>
        <name>[HAB84] 77</name>
        <name>HD 224803</name>
        <name>HD 224803</name>
        <name>HD 224803</name>
        <name>HD   2345</name>
        <name>HD   2345</name>
        <name>HD   2345</name>
        <name>HIP 70</name>
        <name>HIP 70</name>
        <name>JW  494</name>
        <name>[KPM2006]   4</name>
        <name>[KPM2006]   4</name>
        <name>LV 3</name>
        <name>Parenago  1866</name>
        <name>Parenago  1867</name>
        <name>Parenago  1867</name>
        <name>Parenago  1912</name>
        <name>Parenago  1912</name>
    <name>SearchFTT generated</name>
        <name>* tet01 Ori A</name>
        <name>* tet01 Ori A</name>
        <name>* tet01 Ori B</name>
        <name>* tet01 Ori B</name>
        <name>* tet01 Ori B</name>
        <name>* tet01 Ori C</name>
        <name>* tet01 Ori C</name>
        <name>* tet01 Ori C</name>
        <name>* tet01 Ori D</name>
        <name>* tet01 Ori D</name>
        <name>* tet01 Ori D</name>
        <name>* tet01 Ori E</name>
        <name>* tet01 Ori E</name>
        <name>* tet01 Ori F</name>
        <name>* tet01 Ori G</name>
        <name>* tet01 Ori H</name>
        <name>VLTI Period 113</name>
        <name>V* V348 Ori</name>
        <nightRestriction>true</nightRestriction>
        <PMDEC>0.013</PMDEC>
        <PMDEC>-0.083</PMDEC>
        <PMDEC>0.0</PMDEC>
        <PMDEC>0.118</PMDEC>
        <PMDEC>0.118</PMDEC>
        <PMDEC>0.118</PMDEC>
        <PMDEC>-0.243</PMDEC>
        <PMDEC>-0.243</PMDEC>
        <PMDEC>0.25</PMDEC>
        <PMDEC>0.25</PMDEC>
        <PMDEC>0.393</PMDEC>
        <PMDEC>0.393</PMDEC>
        <PMDEC>0.393</PMDEC>
        <PMDEC>0.429</PMDEC>
        <PMDEC>0.429</PMDEC>
        <PMDEC>-0.907</PMDEC>
        <PMDEC>0.994</PMDEC>
        <PMDEC>0.994</PMDEC>
        <PMDEC>0.994</PMDEC>
        <PMDEC>-0</PMDEC>
        <PMDEC>-0</PMDEC>
        <PMDEC>-0</PMDEC>
        <PMDEC>-0</PMDEC>
        <PMDEC>-0</PMDEC>
        <PMDEC>1.186</PMDEC>
        <PMDEC>1.186</PMDEC>
        <PMDEC>-1223.07</PMDEC>
        <PMDEC>-1223.07</PMDEC>
        <PMDEC>1.278</PMDEC>
        <PMDEC>1.278</PMDEC>
        <PMDEC>1.278</PMDEC>
        <PMDEC>1.524</PMDEC>
        <PMDEC>-1.717</PMDEC>
        <PMDEC>-1.735</PMDEC>
        <PMDEC>-21.605</PMDEC>
        <PMDEC>-21.605</PMDEC>
        <PMDEC>-22.343</PMDEC>
        <PMDEC>-22.343</PMDEC>
        <PMDEC>-22.343</PMDEC>
        <PMDEC>2.393</PMDEC>
        <PMDEC>-43.67</PMDEC>
        <PMDEC>-43.67</PMDEC>
        <PMDEC>-5.161</PMDEC>
        <PMDEC>-5.161</PMDEC>
        <PMDEC>5.296</PMDEC>
        <PMDEC>5.296</PMDEC>
        <PMDEC>5.296</PMDEC>
        <PMDEC>-5.563</PMDEC>
        <PMDEC>-5.563</PMDEC>
        <PMDEC>-914.52</PMDEC>
        <PMRA>0.0</PMRA>
        <PMRA>0.152</PMRA>
        <PMRA>0.152</PMRA>
        <PMRA>0.722</PMRA>
        <PMRA>-0</PMRA>
        <PMRA>-0</PMRA>
        <PMRA>-0</PMRA>
        <PMRA>-0</PMRA>
        <PMRA>-0</PMRA>
        <PMRA>1.107</PMRA>
        <PMRA>1.212</PMRA>
        <PMRA>1.28</PMRA>
        <PMRA>1.28</PMRA>
        <PMRA>1.28</PMRA>
        <PMRA>1.345</PMRA>
        <PMRA>1.345</PMRA>
        <PMRA>1.355</PMRA>
        <PMRA>1.355</PMRA>
        <PMRA>1.59</PMRA>
        <PMRA>17.989</PMRA>
        <PMRA>17.989</PMRA>
        <PMRA>17.989</PMRA>
        <PMRA>1.822</PMRA>
        <PMRA>1.822</PMRA>
        <PMRA>1.822</PMRA>
        <PMRA>19.34</PMRA>
        <PMRA>19.34</PMRA>
        <PMRA>2.087</PMRA>
        <PMRA>2.113</PMRA>
        <PMRA>2.113</PMRA>
        <PMRA>2.113</PMRA>
        <PMRA>2.262</PMRA>
        <PMRA>2.262</PMRA>
        <PMRA>2.262</PMRA>
        <PMRA>2.289</PMRA>
        <PMRA>2.289</PMRA>
        <PMRA>-24.63</PMRA>
        <PMRA>-24.63</PMRA>
        <PMRA>-24.63</PMRA>
        <PMRA>-25.179</PMRA>
        <PMRA>-25.179</PMRA>
        <PMRA>2.54</PMRA>
        <PMRA>-461.571</PMRA>
        <PMRA>5.314</PMRA>
        <PMRA>-546.01</PMRA>
        <PMRA>-546.01</PMRA>
        <PMRA>6.41</PMRA>
        <PMRA>6.41</PMRA>
        <PMRA>6.639</PMRA>
        <PMRA>6.639</PMRA>
        <pops></pops>
        <RA/>
        <RA/>
        <RA>0.20272295647000002</RA>
        <RA>0.20272295647000002</RA>
        <RA>0.20702433180999996</RA>
        <RA>0.20702433180999996</RA>
        <RA>0.20702433180999996</RA>
        <RA>101.28715533333335</RA>
        <RA>101.28715533333335</RA>
        <RA>101.28876746876543</RA>
        <RA>56.871152303749994</RA>
        <RA>56.871152303749994</RA>
        <RA>6.79965249707</RA>
        <RA>6.79965249707</RA>
        <RA>6.79965249707</RA>
        <RA>83.6218664744031</RA>
        <RA>83.6218664744031</RA>
        <RA>83.6218664744031</RA>
        <RA>83.621951907</RA>
        <RA>83.621951907</RA>
        <RA>83.62273598326</RA>
        <RA>83.6231106557</RA>
        <RA>83.6231106557</RA>
        <RA>83.81514703646</RA>
        <RA>83.81554420913541</RA>
        <RA>83.81571742286</RA>
        <RA>83.81571742286</RA>
        <RA>83.81580416666667</RA>
        <RA>83.81593917292</RA>
        <RA>83.81593917292</RA>
        <RA>83.81595833333333</RA>
        <RA>83.81599697065457</RA>
        <RA>83.81599697065457</RA>
        <RA>83.8161587334</RA>
        <RA>83.81722494169</RA>
        <RA>83.81722494169</RA>
        <RA>83.81722494169</RA>
        <RA>83.81786633459</RA>
        <RA>83.8186095697</RA>
        <RA>83.8186095697</RA>
        <RA>83.8186095697</RA>
        <RA>83.81967916666666</RA>
        <RA>83.81969609357</RA>
        <RA>83.82190603333</RA>
        <RA>83.82190603333</RA>
        <RA>83.82190603333</RA>
        <RA>83.82190603333</RA>
        <RA>83.82277458142</RA>
        <RA>83.82425582523</RA>
        <RA>83.82425582523</RA>
        <samplingPeriod>60.0</samplingPeriod>
    <schemaVersion>2018.04</schemaVersion><!--Remove to propose coordinates refresh (may be part of a form parameter to add it) <targetVersion>2019.09</targetVersion>-->
    <selectedTargets>Sirius_B</selectedTargets>
        <stations>UT1 UT2 UT3 UT4</stations>
    </target>
    </target>
    </target>
    </target>
    </target>
    </target>
    </target>
    </target>
    </target>
    </target>
    </target>
    </target>
    </target>
    </target>
    </target>
    </target>
    </target>
    </target>
    </target>
    </target>
    </target>
    </target>
    </target>
    </target>
    </target>
    </target>
    </target>
    </target>
    </target>
    </target>
    </target>
    </target>
    </target>
    </target>
    </target>
    </target>
    </target>
    </target>
    </target>
    </target>
    </target>
    </target>
    </target>
    </target>
    </target>
    </target>
    </target>
    </target>
    </target>
    </target><!--
    <target id="2MASS_J05342926-0523509">
    <target id="83.82190603333_-5.387936316139999">
    <target id="__alf_CMa">
    <target id="__alf_CMa_B">
    <target id="Brun_283">
    <target id="coup_1">
    <target id="coup_2">
    <target id="COUP___885">
    <target id="eta_tau">
    <target id="__eta_Tau">
    <target id="Gaia_DR3_2374964121227201024">
    <target id="Gaia_DR3_2880169682463575936">
    <target id="Gaia_DR3_2880169888622006272">
    <target id="Gaia_DR3_3017363960251507712">
    <target id="Gaia_DR3_3017364059023821696">
    <target id="Gaia_DR3_3017364063323198080">
    <target id="Gaia_DR3_3017364063330465152">
    <target id="Gaia_DR3_3017364063330718080">
    <target id="Gaia_DR3_3017364063331576192">
    <target id="Gaia_DR3_3017364127743288320">
    <target id="Gaia_DR3_3017364127743288704">
    <target id="Gaia_DR3_3017364132049943680">
    <target id="Gaia_DR3_3017364132050194688">
    <target id="Gaia_DR3_3209424482420904448">
    <target id="Gaia_DR3_3209424486715714432">
    <target id="Gaia_DR3_3209424486715714816">
    <target id="Gaia_DR3_66714384142368256">
    <target id="_HAB84__77">
    <target id="HD_224803">
    <target id="HD224803">
    <target id="HD___2345">
    <target id="HD2345">
    <target id="HIP_70">
    <target id="JW__494">
    <target id="_KPM2006____4">
    <target id="LV_3">
    <target id="Parenago__1867">
    <target id="Parenago__1912">
    <target id="Sirius">
    <target id="__tet01_Ori_A">
    <target id="__tet01_Ori_B">
    <target id="tet01_Ori_B">
    <target id="__tet01_Ori_C">
    <target id="tet01_Ori_C">
    <target id="__tet01_Ori_D">
    <target id="tet01_Ori_D">
    <target id="__tet01_Ori_E">
    <target id="__tet01_Ori_F">
    <target id="__tet01_Ori_G">
    <target id="__tet01_Ori_H">
        </targetInfo>
        </targetInfo>
        </targetInfo>
        </targetInfo>
        </targetInfo>
        </targetInfo>
        </targetInfo>
        </targetInfo>
        </targetInfo>
        </targetInfo>
        <targetInfo>
        <targetInfo>
        <targetInfo>
        <targetInfo>
        <targetInfo>
        <targetInfo>
        <targetInfo>
        <targetInfo>
        <targetInfo>
        <targetInfo>
            <targetRef>83.82190603333_-5.387936316139999</targetRef>
            <targetRef>coup_1</targetRef>
            <targetRef>coup_2</targetRef>
            <targetRef>eta_tau</targetRef>
            <targetRef>HD224803</targetRef>
            <targetRef>HD2345</targetRef>
            <targetRef>Sirius</targetRef>
            <targetRef>tet01_Ori_B</targetRef>
            <targetRef>tet01_Ori_C</targetRef>
            <targetRef>tet01_Ori_D</targetRef>
                <targets>__alf_CMa_B __alf_CMa</targets>
                <targets>__alf_CMa</targets>
                <targets>COUP___885 __tet01_Ori_C __tet01_Ori_D Gaia_DR3_3017364063331576192 Gaia_DR3_3017364063330718080 Gaia_DR3_3017364059023821696 __tet01_Ori_F Gaia_DR3_3017364063330465152 Parenago__1912 __tet01_Ori_G</targets>
                <targets>COUP___885 __tet01_Ori_C __tet01_Ori_D Gaia_DR3_3017364063331576192 Gaia_DR3_3017364063330718080 Gaia_DR3_3017364059023821696 __tet01_Ori_F Gaia_DR3_3017364063330465152 Parenago__1912 __tet01_Ori_G</targets>
                <targets>Gaia_DR3_2374964121227201024 HD___2345</targets>
                <targets>Gaia_DR3_2374964121227201024 HD___2345</targets>
                <targets>Gaia_DR3_2880169888622006272 Gaia_DR3_2880169682463575936 HD_224803 HIP_70</targets>
                <targets>Gaia_DR3_2880169888622006272 Gaia_DR3_2880169682463575936 HD_224803 HIP_70</targets>
                <targets>Gaia_DR3_3209424486715714432 Gaia_DR3_3209424486715714816 2MASS_J05342926-0523509 Brun_283 _KPM2006____4 Gaia_DR3_3209424482420904448</targets>
                <targets>Gaia_DR3_3209424486715714432 Gaia_DR3_3209424486715714816 2MASS_J05342926-0523509 _KPM2006____4 Brun_283 Gaia_DR3_3209424482420904448</targets>
                <targets>Gaia_DR3_3209424486715714816 Brun_283</targets>
                <targets>Gaia_DR3_3209424486715714816 Brun_283</targets>
            <targets>Gaia_DR3_66714384142368256 __eta_Tau __alf_CMa_B __alf_CMa Gaia_DR3_2374964121227201024 HD___2345 __tet01_Ori_A __tet01_Ori_B __tet01_Ori_C __tet01_Ori_D Gaia_DR3_3017364132050194688 Gaia_DR3_3017364127743288704 Gaia_DR3_3017364063330718080 __tet01_Ori_E __tet01_Ori_F Gaia_DR3_3017364063330465152 Gaia_DR3_3017364132049943680 __tet01_Ori_A __tet01_Ori_B __tet01_Ori_C __tet01_Ori_D Gaia_DR3_3017364132050194688 Gaia_DR3_3017364127743288704 Gaia_DR3_3017364063330718080 __tet01_Ori_E __tet01_Ori_F Gaia_DR3_3017364063330465152 Gaia_DR3_3017364132049943680 Gaia_DR3_3209424486715714816 Brun_283 __tet01_Ori_A __tet01_Ori_B __tet01_Ori_C __tet01_Ori_D Gaia_DR3_3017364132050194688 Gaia_DR3_3017364127743288704 Gaia_DR3_3017364063330718080 __tet01_Ori_E __tet01_Ori_F Gaia_DR3_3017364063330465152 Gaia_DR3_3017364132049943680 __tet01_Ori_A __tet01_Ori_B __tet01_Ori_C __tet01_Ori_D Gaia_DR3_3017364132050194688 Gaia_DR3_3017364127743288704 Gaia_DR3_3017364063330718080 __tet01_Ori_E __tet01_Ori_F Gaia_DR3_3017364063330465152 Gaia_DR3_3017364132049943680 Gaia_DR3_3209424486715714816 Brun_283 Gaia_DR3_2880169888622006272 Gaia_DR3_2880169682463575936 HD_224803 HIP_70</targets>
            <targets>Gaia_DR3_66714384142368256 __eta_Tau __alf_CMa Gaia_DR3_2374964121227201024 HD___2345 __tet01_Ori_C Gaia_DR3_3017364132050194688 Gaia_DR3_3017364063331576192 Gaia_DR3_3017364063330718080 __tet01_Ori_F Gaia_DR3_3017364063330465152 Gaia_DR3_3017364063323198080 __tet01_Ori_G Gaia_DR3_3017363960251507712 Parenago__1867 __tet01_Ori_H LV_3 COUP___885 __tet01_Ori_C __tet01_Ori_D Gaia_DR3_3017364063331576192 Gaia_DR3_3017364063330718080 Gaia_DR3_3017364059023821696 __tet01_Ori_F Gaia_DR3_3017364063330465152 Parenago__1912 __tet01_Ori_G Gaia_DR3_3209424486715714432 Gaia_DR3_3209424486715714816 2MASS_J05342926-0523509 _KPM2006____4 Brun_283 Gaia_DR3_3209424482420904448 __tet01_Ori_A __tet01_Ori_B Gaia_DR3_3017364132050194688 Gaia_DR3_3017364127743288704 JW__494 _HAB84__77 Gaia_DR3_3017364063331576192 __tet01_Ori_E Gaia_DR3_3017364127743288320 Gaia_DR3_3017364132049943680 COUP___885 __tet01_Ori_C __tet01_Ori_D Gaia_DR3_3017364063331576192 Gaia_DR3_3017364063330718080 Gaia_DR3_3017364059023821696 __tet01_Ori_F Gaia_DR3_3017364063330465152 Parenago__1912 __tet01_Ori_G Gaia_DR3_3209424486715714432 Gaia_DR3_3209424486715714816 2MASS_J05342926-0523509 Brun_283 _KPM2006____4 Gaia_DR3_3209424482420904448 Gaia_DR3_2880169888622006272 Gaia_DR3_2880169682463575936 HD_224803 HIP_70</targets>
                <targets>Gaia_DR3_66714384142368256 __eta_Tau</targets>
                <targets>Gaia_DR3_66714384142368256 __eta_Tau</targets>
                <targets>__tet01_Ori_A __tet01_Ori_B Gaia_DR3_3017364132050194688 Gaia_DR3_3017364127743288704 JW__494 _HAB84__77 Gaia_DR3_3017364063331576192 __tet01_Ori_E Gaia_DR3_3017364127743288320 Gaia_DR3_3017364132049943680</targets>
                <targets>__tet01_Ori_A __tet01_Ori_B __tet01_Ori_C __tet01_Ori_D Gaia_DR3_3017364132050194688 Gaia_DR3_3017364127743288704 Gaia_DR3_3017364063330718080 __tet01_Ori_E __tet01_Ori_F Gaia_DR3_3017364063330465152 Gaia_DR3_3017364132049943680</targets>
                <targets>__tet01_Ori_A __tet01_Ori_B __tet01_Ori_C __tet01_Ori_D Gaia_DR3_3017364132050194688 Gaia_DR3_3017364127743288704 Gaia_DR3_3017364063330718080 __tet01_Ori_E __tet01_Ori_F Gaia_DR3_3017364063330465152 Gaia_DR3_3017364132049943680</targets>
                <targets>__tet01_Ori_A __tet01_Ori_B __tet01_Ori_C __tet01_Ori_D Gaia_DR3_3017364132050194688 Gaia_DR3_3017364127743288704 Gaia_DR3_3017364063330718080 __tet01_Ori_E __tet01_Ori_F Gaia_DR3_3017364063330465152 Gaia_DR3_3017364132049943680</targets>
                <targets>__tet01_Ori_A __tet01_Ori_B __tet01_Ori_C __tet01_Ori_D Gaia_DR3_3017364132050194688 Gaia_DR3_3017364127743288704 Gaia_DR3_3017364063330718080 __tet01_Ori_E __tet01_Ori_F Gaia_DR3_3017364063330465152 Gaia_DR3_3017364132049943680</targets>
                <targets>__tet01_Ori_C Gaia_DR3_3017364132050194688 Gaia_DR3_3017364063331576192 Gaia_DR3_3017364063330718080 __tet01_Ori_F Gaia_DR3_3017364063330465152 Gaia_DR3_3017364063323198080 __tet01_Ori_G Gaia_DR3_3017363960251507712 Parenago__1867 __tet01_Ori_H LV_3</targets>
    </targetUserInfos>
    <targetUserInfos>
    </variant>
    <variant>
    <when>
    </when><!--<interferometerConfiguration>
